name: CI
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use node 12
        uses: actions/setup-node@v2
        with:
          node-version: '12'
      - name: Install, link plugin locally, and test
        run: |
          yarn install
          yarn link
          yarn link lighthouse-plugin-field-performance
          yarn test
